# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceeb93bbd5277f4a0ba8b8e3473aca544e8f2e3f6eb52634377a320e683fc049491011b558c6eb9715c31fe745a78f4d7d94fedab6b79dbd764d7f05ed91f54e

test:
  secret_key_base: 3b1bb31804ceb46f64ecb3dcc0011411d6bf243e31521cefee3416646c571f5869faac68f0bc9e6bdc1b04ceb2309ffe68c0670ee2314bd157709f071c9d8cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
